---
functional:
  - Организация дуэли между двумя игроками: создание матча, подбор оппонента по рейтингу, приглашение по ссылке.
  - Режим "игра с ботом" с настраиваемым уровнем сложности.
  - Рейтинговая система и лидерборд: расчёт рейтинга после матча, отображение мест и истории рейтинга.
  - Набор задач (каталог задач) с категориями и уровнями сложности, возможность добавления/редактирования задач.
  - Редактор кода с подсветкой синтаксиса, поддержкой нескольких языков, автосохранением и историей изменений.
  - Реальное отображение действий оппонента (live‑view) и режим наблюдателя (spectator).
  - Система запуска и проверки решений: автотесты, таймауты, ограничение ресурсоёмкости, изоляция выполнения (песочница).
  - Таймер матча, управление временем и правило окончания матча (timeout / accepted / points).
  - Чат/сообщения во время матча, возможности mute/report, базовая модерация.
  - Профили пользователей: статистика, история игр, возможность настройки публичности профиля.
  - Просмотр истории партии и реплей матча (воспроизведение ходов по шагам).
  - Создание приватных и публичных матчей, настройки видимости и приглашений.

non-functional:
  - Удобство использования: интуитивный интерфейс, удобная навигация, понятные сообщения об ошибках.
  - Адаптивность: корректная работа на мобильных устройствах и планшетах (mobile‑first подход).
  - Производительность: низкая задержка realtime‑обновлений (<200 ms в идеале), сайт способен обрабатывать минимум 1000 одновременных пользователей.
  - Масштабируемость: архитектура, позволяющая горизонтальное масштабирование (stateless‑сервисы, использование очередей/Redis для pub/sub).
  - Надёжность и доступность: целевая доступность (SLA) например 99.9%, обработка ошибок и graceful degradation.
  - Безопасность: HTTPS, безопасное хранение паролей и секретов, защита от CSRF/XSS/SQL‑инъекций, rate limiting.
  - Тестируемость: автоматические unit, integration и end‑to‑end тесты; регулярные прогонки нагрузочных тестов.
  - Поддерживаемость: документированный код, стандарты кодирования, README и CONTRIBUTING для разработчиков.
  - Мониторинг и логирование: метрики производительности, алерты, централизованные логи и трейсинг.
  - Совместимость с браузерами: корректная работа в последних версиях Chrome, Firefox, Safari и Edge.

implicit:
  - Соответствие требованиям приватности и законодательству (например, GDPR): явное согласие на обработку данных, возможность удаления аккаунта и данных.
  - Доступность (accessibility): соответствие WCAG 2.1 (минимум уровень AA) для ключевых интерфейсов.
  - Международная поддержка: возможность локализации интерфейса (RU/EN как минимум) и добавления новых языков.
  - Политики хранения и резервного копирования данных: регулярные бэкапы и план восстановления после сбоя.
  - Механизмы борьбы с читерством и мошенничеством: логирование действий, анализ подозрительных паттернов, ограничение запуска задач.
  - Открытость проекта: наличие правил вклада (CONTRIBUTING), кодекса поведения (CODE_OF_CONDUCT) и минимального набора developer docs.
